#!/usr/bin/perl
use strict;
use warnings;
use File::Find;
use v5.030;

my $source_path = $ARGV[0] || '.';

my $all = 0;
my $code = 0;
my $comments = 0;

sub process_file {
	return unless /\.go$/;
	open my ($fd), $_;
	while (<$fd>) {
		$all++;

		# skip empty/whitespace lines
		next if /^\s*$/;

		# count comments
		if (m{^\s*//}) {
			$comments++;
			next;
		}

		# count code lines
		$code++;
	}
	close $fd;
}

find(\&process_file, $source_path);

my $nonblank = $code + $comments;
die 'no matching source code found' unless $nonblank;

my $code_percent = $code / $nonblank * 100;
my $comments_percent = 100 - $code_percent;

say 'all       : ', $all;
say 'blank     : ', $all - $nonblank;
say 'nonblank  : ', $nonblank;
say 'code      : ', $code;
say '%code     : ', $code_percent;
say 'comments  : ', $comments;
say '%comments : ', $comments_percent;
