#!/usr/bin/perl

use strict;
use warnings;
use OpenBSD::Pledge;
use OpenBSD::Unveil;
use HTTP::Tiny;

unveil('/', '') or die $!;
pledge(qw( rpath dns inet )) or die $!;

my $http = HTTP::Tiny->new();

sub slurp
{
	my ($fh) = @_;
	local $/;
	return <$fh>;
}

sub sprunge
{
	my ($input) = @_;
	my $url = 'http://sprunge.us';
	my $form = [ sprunge => $input ];
	my $resp = $http->post_form($url, $form)
	    or die "could not POST: $!";
	return $resp->{content};
}

my $input = slurp('STDIN');
my $url = sprunge($input);
print $url;
